- contributor_iri: https://orcid.org/0000-0001-8900-6203
  contributor_literal: Lee Belbin
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Blatant Fabrications
  affiliation_uri: https://www.wikidata.org/wiki/Q130304884

- contributor_iri: https://orcid.org/0000-0003-1700-6962
  contributor_literal: Arthur D. Chapman
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Australian Biodiversity Information Services
  affiliation_uri: http://www.wikidata.org/entity/Q100600913

- contributor_iri: https://orcid.org/0000-0002-3673-444X
  contributor_literal: Paul J. Morris
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Museum of Comparative Zoology, Harvard University
  affiliation_uri: http://www.wikidata.org/entity/Q1420782

- contributor_iri: https://orcid.org/0000-0003-1144-0290
  contributor_literal: John Wieczorek
  contributor_role: author
  role_uri: http://www.wikidata.org/entity/Q482980
  affiliation: Rauthiflor LLC
  affiliation_uri: 

- contributor_iri: https://orcid.org/0000-0001-7087-2646
  contributor_literal: Yi-Ming Gan
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Royal Belgian Institute of Natural Sciences
  affiliation_uri: http://www.wikidata.org/entity/Q16665660

- contributor_iri: https://orcid.org/0000-0003-2283-1123
  contributor_literal: António Mauro Saraiva
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Universidade de São Paulo
  affiliation_uri: https://www.wikidata.org/wiki/Q835960

- contributor_iri: http://orcid.org/0000-0003-2672-8115 
  contributor_literal: Alan Koch Veiga
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Universidade de São Paulo
  affiliation_uri: https://www.wikidata.org/wiki/Q835960

- contributor_iri: https://orcid.org/0000-0002-6056-5084
  contributor_literal: Paula F Zermoglio 
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 'Instituto de Investigaciones en Recursos Naturales, Agroecología y Desarrollo Rural (IRNAD, CONICET-UNRN): San Carlos de Bariloche'
  affiliation_uri: https://www.irnad.com/

- contributor_iri: https://orcid.org/0000-0002-8981-4048
  contributor_literal: Alexander Thompson
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Google
  affiliation_uri: https://www.wikidata.org/wiki/Q95

- contributor_iri: https://github.com/lowery
  contributor_literal: David Lowery
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: 
  affiliation_uri: 

- contributor_iri: https://orcid.org/0000-0003-4898-4291
  contributor_literal: Christian Gendreau
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Agriculture and Agri-Food Canada
  affiliation_uri: http://www.wikidata.org/entity/Q1046164

- contributor_iri: https://orcid.org/0000-0001-6215-3617
  contributor_literal: Tim Roberston
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Global Biodiversity Information Facility
  affiliation_uri: https://www.wikidata.org/wiki/Q1531570

- contributor_iri: https://orcid.org/0000-0002-2919-1168
  contributor_literal: Dmitry Schigel
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Global Biodiversity Information Facility
  affiliation_uri: https://www.wikidata.org/wiki/Q1531570

- contributor_iri: https://orcid.org/0000-0002-6992-9446
  contributor_literal: Robert A. Morris
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation:
  affiliation_uri:

- contributor_iri: https://orcid.org/0000-0002-3302-0070
  contributor_literal: Miles Nicholls
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Atlas of Living Australia
  affiliation_uri: https://www.wikidata.org/wiki/Q16335177

- contributor_iri: https://orcid.org/0000-0003-0112-6716
  contributor_literal: Emily Rose Rees
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: Atlas of Living Australia
  affiliation_uri: https://www.wikidata.org/wiki/Q16335177

- contributor_iri: https://orcid.org/0000-0002-4391-107X
  contributor_literal: Abigail Benson
  contributor_role: contributor
  role_uri: http://www.wikidata.org/entity/Q20204892
  affiliation: U.S. Geological Survey
  affiliation_uri: https://www.wikidata.org/wiki/Q193755
